// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package stringstore

import (
	"errors"
	"fmt"
	"math/big"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	GetStringGasCost uint64 = 1 /* SET A GAS COST HERE */
	SetStringGasCost uint64 = 1 /* SET A GAS COST HERE */
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
)

// Singleton StatefulPrecompiledContract and signatures.
var (

	// StringStoreRawABI contains the raw ABI of StringStore contract.
	//go:embed contract.abi
	StringStoreRawABI string

	StringStoreABI = contract.ParseABI(StringStoreRawABI)

	StringStorePrecompile = createStringStorePrecompile()

	storageKeyHash = common.BytesToHash([]byte("storageKey"))
)

// PackGetString packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetString() ([]byte, error) {
	return StringStoreABI.Pack("getString")
}

// PackGetStringOutput attempts to pack given value of type string
// to conform the ABI outputs.
func PackGetStringOutput(value string) ([]byte, error) {
	return StringStoreABI.PackOutput("getString", value)
}

// GetString returns the value of the storage key "storageKey" in the contract storage,
// with leading zeroes trimmed.
func GetString(stateDB contract.StateDB) string {
	// Get the value set at recipient
	value := stateDB.GetState(ContractAddress, storageKeyHash)
	return string(common.TrimLeftZeroes(value.Bytes()))
}

func getString(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetStringGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE

	var output string // CUSTOM CODE FOR AN OUTPUT

	currentState := accessibleState.GetStateDB()
	output = GetString(currentState)

	packedOutput, err := PackGetStringOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSetStringInput attempts to unpack [input] into the string type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSetStringInput(input []byte) (string, error) {
	res, err := StringStoreABI.UnpackInput("setString", input)
	if err != nil {
		return "", err
	}
	unpacked := *abi.ConvertType(res[0], new(string)).(*string)
	return unpacked, nil
}

// PackSetString packs [value] of type string into the appropriate arguments for setString.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackSetString(value string) ([]byte, error) {
	return StringStoreABI.Pack("setString", value)
}

// StoreString sets the value of the storage key "storageKey" in the contract storage.
func StoreString(stateDB contract.StateDB, newValue string) {
	newValuePadded := common.LeftPadBytes([]byte(newValue), common.HashLength)
	newValueHash := common.BytesToHash(newValuePadded)

	stateDB.SetState(ContractAddress, storageKeyHash, newValueHash)
}

func setString(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SetStringGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the SetStringInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackSetStringInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// CUSTOM CODE STARTS HERE
	// Get K-V Mapping
	currentState := accessibleState.GetStateDB()

	// Set the value
	StoreString(currentState, inputStruct)

	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createStringStorePrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.

func createStringStorePrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"getString": getString,
		"setString": setString,
	}

	for name, function := range abiFunctionMap {
		method, ok := StringStoreABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
